Code Review for <setup-associations> | Ruby School Library App
luigirazum/ruby-school-library-app pull request #3
Opened 2023-05-25 05:13 UTC by luigirazum

# Hello Dear Code Reviewers Team 👋,
## I would like to ask for your kindly help to do the 🔍 Code Review 👀 for my project.
### The following requirements 📌 were fulfilled this time:
#### - 🎯 General requirements
- 📌 Make sure that there are no linter errors.
  - ✅ Linters for Ruby were installed. `Rubocop` reported no errors.
- 📌 Make sure that you used the correct GitFlow.
  - ✅ `setup-associations` feature branch was created from `dev` to follow the `git-flow`.
- 📌 Make sure that you documented your work in a professional way.
  - ✅ `README` file was updated with all the Project 3/7 details.
#### - 🎯 Ruby requirements
- 📌 Follow the list of best practices for Ruby.
  - ✅ Best practices for `Ruby` were followed.
#### - 🎯 Project requirements
Create the remaining <kbd>Classes</kbd> for our **Ruby School Library App** and create the <kbd>Associations</kbd> between them.
- 📌 Create a class <kbd>Classroom</kbd> with the following:
  - 🚩 `@label` instance variable, should be initialized in the constructor.
  - 🚩 Setter and getter for `@label` (remember about `attr_accessor`).
- 📌 Create the `has-many`/`belongs-to` relationship between <kbd>Classroom</kbd> and <kbd>Student</kbd>.
The following should be implemented:
  - 🚩 Create the `has-many` side (a <kbd>Classroom</kbd> has many <kbd>Student</kbd>s).
  - 🚩 Create the `belongs-to` side (a <kbd>Student</kbd> belongs to a <kbd>Classroom</kbd>).
  - 🚩 Make sure that when adding a <kbd>Student</kbd> to a <kbd>Classroom</kbd> it also sets the <kbd>Classroom</kbd> for the <kbd>Student</kbd>.
  - 🚩 Make sure that when setting the <kbd>Classroom</kbd> for a <kbd>Student</kbd> it also adds it to the <kbd>Classroom</kbd>s' <kbd>Student</kbd>s.
- 📌 Create a class <kbd>Book</kbd> with the following:
  - 🚩 `@title` and `@author` instance variables, should be initialized in the constructor.
  - 🚩 Setters and getters for instance variables (remember about `attr_accessor`).
- 📌 Create a class <kbd>Rental</kbd> with the following:
  - 🚩 `@date` instance variable, should be initialized in the constructor.
  - 🚩 Setter and getter for `@date` (remember about `attr_accessor`).
- 📌 Create the `many-to-many` (also `has-many-through`) relationship between <kbd>Person</kbd> and <kbd>Book</kbd> using the intermediate class <kbd>Rental</kbd>.
The following should be implemented:
  - 🚩 Create the `has-many` side of <kbd>Book</kbd> and <kbd>Rental</kbd> (a <kbd>Book</kbd> has many <kbd>Rental</kbd>s).
  - 🚩 Create the `belongs-to` side of <kbd>Rental</kbd> and <kbd>Book</kbd> (a <kbd>Rental</kbd> belongs to a <kbd>Book</kbd>).
  - 🚩 Create the `has-many` side of <kbd>Person</kbd> and <kbd>Rental</kbd> (a <kbd>Person</kbd> has many <kbd>Rental</kbd>s).
  - 🚩 Create the `belongs-to` side of <kbd>Rental</kbd> and <kbd>Person</kbd> (a <kbd>Rental</kbd> belongs to a <kbd>Person</kbd>).
  - 🚩 Modify the constructor of <kbd>Rental</kbd> so <kbd>Book</kbd> and <kbd>Person</kbd> are set in it.

### I really thank you for your support. 🙏
### Cheers and Happy Reviewing! 👀
### Luis 🙋‍♂️

2023-05-25 21:03 UTC, Deepakdanger requested changes
Hi @luigirazum , 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 
- Website looks professional :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 21:03 UTC, Deepakdanger commented on classes/person.rb
>    attr_accessor :name, :age
- [ ] There is no need of `id` in attr_reader & `rentals` will be included in attr_accessor.

2023-05-25 21:03 UTC, Deepakdanger commented on classes/person.rb
> +  # a 'Person' <has-many> 'Rental's
- [ ] Here we should also write a method to `add_rental` here
```ruby
 def add_rental(book, date)
    # *The person itself should be sent as a parameter to create the new rental achieving the 'has-many' association
    Rental.new(date, book, self)
  end
```

2023-05-25 23:38 UTC, luigirazum commented on classes/book.rb
> +  attr_accessor :title, :author
https://github.com/luigirazum/ruby-school-library-app/pull/3/commits/772e61e54da47f4fa3597ff82a8e0e01f6d8f719#diff-ee4e22a5d6ed72e9d0c08b0c1ed23e071d4beb1356e34e6def30ebee8a08a454R1-L3

2023-05-25 23:43 UTC, luigirazum commented on classes/book.rb
> +  attr_accessor :title, :author
All right! It's done!

2023-05-26 00:07 UTC, luigirazum commented on classes/book.rb
> +  end
Thanks for the feedback... the change is done!

2023-05-26 00:10 UTC, luigirazum commented on classes/person.rb
>    attr_accessor :name, :age
Done with that too!

2023-05-26 00:13 UTC, luigirazum commented on classes/person.rb
> +  # a 'Person' <has-many> 'Rental's
Fixed this one too!

2023-05-26 00:31 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @luigirazum, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 00:33 UTC, merged